# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2LeNF2TiwbJq6TeYOY2VODS572gVLj1
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.columns[0]

df.isna

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary'].max()

row = clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'][row]

clean_df['Mid-Career Median Salary'].max()

row = clean_df['Mid-Career Median Salary'].idxmax()

clean_df['Mid-Career Median Salary'][row]

clean_df['Undergraduate Major'][row]

clean_df['Starting Median Salary'].min()

row = clean_df['Starting Median Salary'].idxmin()

clean_df['Undergraduate Major'][row]

clean_df['Mid-Career Median Salary'].min()

row = clean_df['Mid-Career Median Salary'].idxmin()

clean_df['Mid-Career Median Salary'][row]

clean_df['Undergraduate Major'][row]
#

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

clean_df.insert(1, 'spread', spread_col)

clean_df.head()

clean_df.sort_values('spread')

clean_df.head()

low_risk = clean_df.sort_values('spread')
low_risk[['Undergraduate Major', 'spread']].head()

highest_potential = clean_df['Mid-Career 90th Percentile Salary'].sort_values(ascending=False)
highest_potential[('Undergraduate Major', 'Mid-Career 90th Percentile Salary')].head()

highest_potential = clean_df.sort_values(by='Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

highest_spread = clean_df.sort_values('spread', ascending=False)
highest_spread[['Undergraduate Major', 'spread']].head()

clean_df.head()

clean_df.groupby('Group').mean()

clean_df.groupby('Group').mean()

clean_df.groupby('Group').mean(numeric_only=True)

pd.options.display.float_format = '{:,.2f}'.format

clean_df.groupby('Group').mean(numeric_only=True)

